<?php
namespace Modules\Kost\Database\factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Modules\Kost\Entities\Kost;

class KostFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' => $this->faker->colorName(),
            'address' => $this->faker->streetName(),
            'price' => rand(100, 1000) * 1000,
            'slot' => rand(1, 10),
            'description' =>$this->faker->text(rand(50, 70))
        ];
    }

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return Kost::class;
    }
}

